In [53]:
import pandas as pd
#Load the dataset
df = pd.read_csv("trends.csv")
df

      location  year         category  rank                query
0       Global  2001  Consumer Brands     1                Nokia
1       Global  2001  Consumer Brands     2                 Sony
2       Global  2001  Consumer Brands     3                  BMW
3       Global  2001  Consumer Brands     4                 Palm
4       Global  2001  Consumer Brands     5                Adobe
...        ...   ...              ...   ...                  ...
26950  Vietnam  2020           Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020           Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020           Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020           Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020           Là Gì?     5       Đông Lào là gì

[26955 rows x 5 columns]

In [54]:
#First 5 rows
df.head()

  location  year         category  rank  query
0   Global  2001  Consumer Brands     1  Nokia
1   Global  2001  Consumer Brands     2   Sony
2   Global  2001  Consumer Brands     3    BMW
3   Global  2001  Consumer Brands     4   Palm
4   Global  2001  Consumer Brands     5  Adobe

In [55]:
#Last 5 rows
df.tail()

      location  year category  rank                query
26950  Vietnam  2020   Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020   Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020   Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020   Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020   Là Gì?     5       Đông Lào là gì

In [56]:
#Number of rows and columns
df.shape

(26955, 5)

In [57]:
#Dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26955 entries, 0 to 26954
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   location  26955 non-null  object
 1   year      26955 non-null  int64
 2   category  26955 non-null  object
 3   rank      26955 non-null  int64
 4   query     26955 non-null  object
dtypes: int64(2), object(3)
memory usage: 1.0+ MB

In [58]:
#Statistical summary
df.describe()

               year         rank
count  26955.000000  26955.00000
mean    2015.243369      3.00000
std        3.564683      1.41424
min     2001.000000      1.00000
25%     2013.000000      2.00000
50%     2016.000000      3.00000
75%     2018.000000      4.00000
max     2020.000000      5.00000

In [59]:
#Column names
df.columns

Index(['location', 'year', 'category', 'rank', 'query'], dtype='object')

In [60]:
#Data types
df.dtypes

location    object
year         int64
category    object
rank         int64
query       object
dtype: object

In [61]:
#Missing values
df.isnull().sum()

location    0
year        0
category    0
rank        0
query       0
dtype: int64

In [62]:
#Duplicate records
df.duplicated().sum()

np.int64(10)

In [63]:
#Unique values
df.nunique()

location       83
year           20
category     2450
rank            5
query       18431
dtype: int64

In [64]:
#Mean
df.mean(numeric_only=True)

year    2015.243369
rank       3.000000
dtype: float64

In [65]:
#Median
df.median(numeric_only=True)

year    2016.0
rank       3.0
dtype: float64

In [66]:
#Minimum
df.min(numeric_only=True)

year    2001
rank       1
dtype: int64

In [67]:
#Maximum
df.max(numeric_only=True)

year    2020
rank       5
dtype: int64

In [68]:
#Standard deviation
df.std(numeric_only=True)

year    3.564683
rank    1.414240
dtype: float64

In [69]:
#Check duplicate rows
df[df.duplicated()]

,location,year,category,rank,query
20000,Kazakhstan,2018,Жылдың фильмі/Фильм года,1,Веном
20001,Kazakhstan,2018,Жылдың фильмі/Фильм года,2,Мстители: Война бесконечности
20002,Kazakhstan,2018,Жылдың фильмі/Фильм года,3,Бизнес по-казахски в Америке
20003,Kazakhstan,2018,Жылдың фильмі/Фильм года,4,Монстры на каникулах 3
20004,Kazakhstan,2018,Жылдың фильмі/Фильм года,5,Дэдпул 2
25400,Kenya,2020,Trending How To (Tech),1,How to fill Tpad online
25401,Kenya,2020,Trending How To (Tech),2,How to create a website
25402,Kenya,2020,Trending How To (Tech),3,How to connect a phone to TV
25403,Kenya,2020,Trending How To (Tech),4,How to make my electric plate cooker work
25404,Kenya,2020,Trending How To (Tech),5,How to take a screenshot on a laptop

In [70]:
#Final cleaning
df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (26945, 5)